services:
  web:
    build: .
    container_name: shorturl
    restart: always
    environment:
      - FLASK_ENV=production
      - SECRET_KEY=mysecretkey
      - DATABASE_URL=sqlite:///../instance/app.db
      - FLASK_DEBUG=False
      - WERKZEUGLOG=False
    volumes:
      - ./instance:/app/instance
    depends_on: []
