version: '3.8'

services:
  web:
    build: .
    container_name: flask_app
    restart: always
    ports:
      - "8000:8000"
    environment:
      - FLASK_ENV=production
      - SECRET_KEY=mysecretkey
      - DATABASE_URL=sqlite:///../instance/app.db
      - FLASK_DEBUG=False
      - WERKZEUGLOG=False
    volumes:
      - ./instance:/app/instance
    depends_on: []
